### ISSUE TITLE
Link to Generate Token section is 403 Forbidden from Authentication section

### ISSUE THREAD

**Issue by j12y** [heremaps/xyz-documentation#11]
Was reported that:

> When I access page u linked and clicked section about tokens I got 403
> 
> https://www.here.xyz/api/getting-token.md
> 
> Looks like md file was not transformed to html?

Looks like the [Authentication](https://www.here.xyz/api/#authentication) details has a link to a **Generate Token** section which is a broken link (403 Forbidden)
https://www.here.xyz/api/getting-token.md

**Comment by j12y** [comment]
The correct url is:
https://www.here.xyz/api/getting-token/

```
diff --git a/docs/api/index.md b/docs/api/index.md
index 272b98d..dcfc07f 100644
--- a/docs/api/index.md
+++ b/docs/api/index.md
@@ -8,7 +8,7 @@ To interact with the HERE XYZ Hub API directly from your application you just ne
 ## Authentication

 For everything you want to do via the API, you need to use a token as described in the
-[Generate Token Section](/api/getting-token.md).
+[Generate Token Section](/api/getting-token).

 [![API](../assets/images/api-auth.png)](../assets/images/api-auth.png)
```

**Comment by olifink** [comment]
thanks, fixed now
