### ISSUE TITLE
Bad link - Useful Links/Maps UI Documentation

### ISSUE THREAD

**Issue by cfjedimaster** [heremaps/xyz-documentation#24]
On this page, https://www.here.xyz/api/links/, the link to https://xyz.api.here.com/public/latest/documentation/ leads to this in the browser:

```
{"message":"Missing Authentication Token"}
```

**Comment by cfjedimaster** [comment]
Sorry, I should say that on the page itself, the link text shows this URL, https://xyz.api.here.com/maps/latest/documentation. I can confirm going there then redirects to the link I shared above and the error.

**Comment by olifink** [comment]
thanks again - good catch, it needs to go to https://xyz.api.here.com/maps/latest/documentation/here.xyz.maps.html now - fixed that
