### ISSUE TITLE
Space ID vs Name

### ISSUE THREAD

**Issue by cfjedimaster** [heremaps/xyz-documentation#25]
On this page, https://www.here.xyz/ui/yourxyzspace/, the sample code shows this:

```js
// Space name
space: 'playground-link',
```

However, spaces don't have a "name". I tried title and it silently failed. When I tried the ID, it worked. I'd change the comment to "Space ID"

**Comment by olifink** [comment]
good point - for the demos we actually created readable ids (while it was still possible, we've since switched to generated ids) - but you are correct that the comment is wrong - it actually needs to be the `Space ID`  there

**Comment by olifink** [comment]
just deployed the changes to playground and documentation
