### ISSUE TITLE
Create link to XYZ Tutorials in Menu

### ISSUE THREAD

**Issue by j12y** [heremaps/xyz-documentation#6]
It is not easy to find the XYZ tutorials since they are not linked from the documentation at here.xyz.  I'd recommend putting a link in the main menu as a good start and integrating them together as a potential longer-term solution to make them easier to discover.

https://codelabs.here.xyz/

**Comment by olifink** [comment]
good point - yes, I'm still going to update the top nav-bar and that should hopefully make it both more approachable as well as link out to the related sites like codelabs

**Comment by olifink** [comment]
ok, this will be fixed with the next deployment in couple of minutes
